### ISSUE TITLE
which feature would be applied by signal? what's this signal for?

### ISSUE THREAD

**Issue by dante01yoon** [dai-shi/create-react-signals#10]
Greetings. What's this signals for? I've been watching this projects for weeks and  see lots of updated  are made. I wonder what's new feature would be affected by this signal?

**Comment by dai-shi** [comment]
This is is started as [jotai-signal](https://github.com/jotai-labs/jotai-signal) project. It's inspired by preactjs/signals-react, and had two goals (a) implementing less hacky with jsx-transform, and (b) utilizes jotai atoms as data sources.
It doesn't add any new use cases compared to normal jotai usage, it's just a different syntax.

This library is a spin-off, and provides the common feature for jotai-signal, valtio-signal and zustand-signal. So, the primary goal is (a) only.
Lately, we had a new idea about bypassing react rendering (which had been experimented in [jotai-uncontrolled](https://github.com/jotai-labs/jotai-uncontrolled) project), and it's implemented now. So, the benefit of this library is both (1) a different syntax that doesn't require react hooks (thus no need to follow hooks rules) and (2) occasional performance improvement (uncontrolled components don't work for all cases).

**Comment by dante01yoon** [comment]
wow, I'm looking forward to these releases. Always appreciate with your OSS works !

**Comment by dai-shi** [comment]
note that what's described is something already released.
